# yaml-language-server: $schema=./.vscode/config.schema.json
system:
  friendly_name: "Chip's MacBook"
  host_name: 'chips-macbook'
symlinks:
  '$REPO_DIR/config/': '$HOME/.config'
  '$REPO_DIR/Brewfile': '$HOME/.Brewfile'
ide: 'cursor'
brew:
  bundle_file: '$HOME/.Brewfile'
  autoupdate: true
  autoupdate_interval: 43200
  cleanup: false
verbose: false
