function __gum_table
    ## style flags
    set -e GUM_TABLE_BORDER_FOREGROUND
    set -e GUM_TABLE_BORDER_BACKGROUND
    set -e GUM_TABLE_CELL_FOREGROUND
    set -e GUM_TABLE_CELL_BACKGROUND
    set -e GUM_TABLE_HEADER_FOREGROUND
    set -e GUM_TABLE_HEADER_BACKGROUND
    set -gx GUM_TABLE_SELECTED_FOREGROUND 212
    set -e GUM_TABLE_SELECTED_BACKGROUND
end
